name = "hents-hurga-api"
main = "worker/src/index.ts"
compatibility_date = "2026-08-08"
compatibility_flags = ["nodejs_compat"]
account_id = "4f092751ca31d58d93a619ad88dc4a2e"
workers_dev = true

[vars]
RFID_DUPLICATE_WINDOW_SECONDS = "300"
ADMIN_EMAILS = "uuganbayrxx0716@gmail.com"
CLERK_AUTHORIZED_PARTIES = "http://localhost:3000,https://henzhurag-123uuganas-projects.vercel.app,https://henzhurag-hki5y06dx-123uuganas-projects.vercel.app"

[dev]
ip = "0.0.0.0"
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "hents-hurag"
database_id = "f4060419-a12b-49db-994e-9ce9c2725686"
migrations_dir = "drizzle"
